//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicicleteWeb.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BicicleteWeb.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actiuni.
        /// </summary>
        public static string Actiuni {
            get {
                return ResourceManager.GetString("Actiuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activ.
        /// </summary>
        public static string Activ {
            get {
                return ResourceManager.GetString("Activ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga O Noua Comanda.
        /// </summary>
        public static string AdaugaComanda {
            get {
                return ResourceManager.GetString("AdaugaComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga in cos.
        /// </summary>
        public static string AdaugaCos {
            get {
                return ResourceManager.GetString("AdaugaCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administreaza Conturi.
        /// </summary>
        public static string AdministreazaConturi {
            get {
                return ResourceManager.GetString("AdministreazaConturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobat.
        /// </summary>
        public static string Aprobat {
            get {
                return ResourceManager.GetString("Aprobat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentificare.
        /// </summary>
        public static string Autentificare {
            get {
                return ResourceManager.GetString("Autentificare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bine ati venit!.
        /// </summary>
        public static string BineAiVenit {
            get {
                return ResourceManager.GetString("BineAiVenit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate:.
        /// </summary>
        public static string Cantitate {
            get {
                return ResourceManager.GetString("Cantitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauta Produs:.
        /// </summary>
        public static string CautaProdus {
            get {
                return ResourceManager.GetString("CautaProdus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola nu corespunde!.
        /// </summary>
        public static string compareValidatorParola {
            get {
                return ResourceManager.GetString("compareValidatorParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare parola.
        /// </summary>
        public static string ConfirmareParola {
            get {
                return ResourceManager.GetString("ConfirmareParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ai cont?Creeaza-ti unul!.
        /// </summary>
        public static string CreareCont {
            get {
                return ResourceManager.GetString("CreareCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culoare:.
        /// </summary>
        public static string Culoare {
            get {
                return ResourceManager.GetString("Culoare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii Comanda.
        /// </summary>
        public static string Detalii {
            get {
                return ResourceManager.GetString("Detalii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre:.
        /// </summary>
        public static string Filtre {
            get {
                return ResourceManager.GetString("Filtre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica comanda si finalizeaza cumparaturile!.
        /// </summary>
        public static string FinalizareComanda {
            get {
                return ResourceManager.GetString("FinalizareComanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizare Comanda.
        /// </summary>
        public static string FinalizareComandaBtn {
            get {
                return ResourceManager.GetString("FinalizareComandaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionati cererile userilor!.
        /// </summary>
        public static string GestioneazaCereri {
            get {
                return ResourceManager.GetString("GestioneazaCereri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactiv.
        /// </summary>
        public static string Inactiv {
            get {
                return ResourceManager.GetString("Inactiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivi.
        /// </summary>
        public static string Inactivi {
            get {
                return ResourceManager.GetString("Inactivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivi si neaprobati.
        /// </summary>
        public static string InactiviNeaprobati {
            get {
                return ResourceManager.GetString("InactiviNeaprobati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inregistrare cu succes!.
        /// </summary>
        public static string InregistrareSucces {
            get {
                return ResourceManager.GetString("InregistrareSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti datele pentru crearea contului!.
        /// </summary>
        public static string IntroducetiDatele {
            get {
                return ResourceManager.GetString("IntroducetiDatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...mai mult.
        /// </summary>
        public static string maiMult {
            get {
                return ResourceManager.GetString("maiMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaprobati.
        /// </summary>
        public static string Neaprobati {
            get {
                return ResourceManager.GetString("Neaprobati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu sunteti administrator!.
        /// </summary>
        public static string NuAdmin {
            get {
                return ResourceManager.GetString("NuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu exista nicio comanda efectuata.
        /// </summary>
        public static string NuExistaComenzi {
            get {
                return ResourceManager.GetString("NuExistaComenzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        public static string Nume {
            get {
                return ResourceManager.GetString("Nume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pret $:.
        /// </summary>
        public static string Pret {
            get {
                return ResourceManager.GetString("Pret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producator:.
        /// </summary>
        public static string Producator {
            get {
                return ResourceManager.GetString("Producator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produs:.
        /// </summary>
        public static string Produs {
            get {
                return ResourceManager.GetString("Produs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produs adaugat in cos!.
        /// </summary>
        public static string ProdusAdaugat {
            get {
                return ResourceManager.GetString("ProdusAdaugat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respins.
        /// </summary>
        public static string Respins {
            get {
                return ResourceManager.GetString("Respins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa Email!.
        /// </summary>
        public static string rfvEmail {
            get {
                return ResourceManager.GetString("rfvEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numele!.
        /// </summary>
        public static string rfvNume {
            get {
                return ResourceManager.GetString("rfvNume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola!.
        /// </summary>
        public static string rfvParola {
            get {
                return ResourceManager.GetString("rfvParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvare Cont.
        /// </summary>
        public static string SalvareCont {
            get {
                return ResourceManager.GetString("SalvareCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toti Utilizatorii.
        /// </summary>
        public static string TotiUtilizatorii {
            get {
                return ResourceManager.GetString("TotiUtilizatorii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datele sunt incorecte sau contul nu a fost aprobat/activat!Reincercati!.
        /// </summary>
        public static string ValidareLogin {
            get {
                return ResourceManager.GetString("ValidareLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoarea Comenzii.
        /// </summary>
        public static string ValoareComanda {
            get {
                return ResourceManager.GetString("ValoareComanda", resourceCulture);
            }
        }
    }
}
